package elk

// alert_status constants
const (
	ALERT_STATUS_NONE = "NONE"
	ALERT_STATUS_QUEUED = "QUEUED"
	ALERT_STATUS_FALSE_POSITIVE = "FALSE_POSITIVE"
	ALERT_STATUS_IGNORE = "IGNORE"
	ALERT_STATUS_UNKNOWN = "UNKNOWN"
	ALERT_STATUS_REVIEWED = "REVIEWED"
	ALERT_STATUS_GRAYWARE = "GRAYWARE"
	ALERT_STATUS_POLICY_VIOLATION = "POLICY_VIOLATION"
	ALERT_STATUS_RECONNAISSANCE = "RECONNAISSANCE"
	ALERT_STATUS_WEAPONIZATION = "WEAPONIZATION"
	ALERT_STATUS_DELIVERY = "DELIVERY"
	ALERT_STATUS_EXPLOITATION = "EXPLOITATION"
	ALERT_STATUS_INSTALLATION = "INSTALLATION"
	ALERT_STATUS_COMMAND_AND_CONTROL = "COMMAND_AND_CONTROL"
	ALERT_STATUS_EXFIL = "EXFIL"
	ALERT_STATUS_DAMAGE = "DAMAGE"
)

// analysis_status constants
const (
	ANALYSIS_STATUS_QUEUED = "QUEUED"
	ANALYSIS_STATUS_ANALYZING = "ANALYZING"
	ANALYSIS_STATUS_COMPLETE = "COMPLETE"
)
